---
title: "Competition-mutualism dynamics"
author: "Gislayne Bueno"
date: '2022-07-24'
output: html_document
---

### Packages

```{r}

library(deSolve)
library(ggplot2) 
library(tidyr)

```

# Main model

$$
\frac {dN_{1}}{dt} =\frac {r_{1}N_{1}}{K_{1}}(K_{1}-(N_{1}+\alpha_{12}N_{2}(1-\frac {N_{1}}{K_{1}}+\frac {N_{2}}{K_{2}})))
$$

```{r include=FALSE}
source("fct/LV_CoMu.R")
```

# Mutualism

In this situation both populations are in low density.

```{r}
# LV parameters
a <- c(0.02, 0.01)
r <- c(1, 1)
K <- c(3500,3000)
p1 <- list(r, a, K)
N0 <- c(10, 10) # N1[1] E N2[2]
t <- c(1:100)
```

```{r}
#Solving the equation

Out_LVcomp <- ode(y = N0, times = t, func = LV_CoMu, parms = p1)
head(Out_LVcomp)

```

```{r}
df_LVcomp <- pivot_longer(as.data.frame(Out_LVcomp), cols = 2:3)
```

```{r}
ggplot(df_LVcomp) +
  geom_line(aes(x = time, y = value, color = name)) +
  labs(x = "Time", y = "N", color = "Species") +
  theme_classic()
```

# Competition

In this situation both populations are in high density.

```{r}
# LV parameters
a <- c(0.02, 0.01)
r <- c(1, 1)
K <- c(3500,3000)
p1 <- list(r, a, K)
N0 <- c(10000, 10000) # N1[1] E N2[2]
t <- c(1:100)
```

```{r}
#Solving the equation

Out_LVmut <- ode(y = N0, times = t, func = LV_CoMu, parms = p1)
head(Out_LVcomp)

```

```{r}
df_LVmut <- pivot_longer(as.data.frame(Out_LVmut), cols = 2:3)
```

```{r}
ggplot(df_LVmut) +
  geom_line(aes(x = time, y = value, color = name)) +
  labs(x = "Time", y = "N", color = "Species") +
  theme_classic()
```

# Outcomes

## Elimination

\$\$ \frac{N_{1}}{K_{1}} = 1 \frac{N_{1}}{K_{1}} = 0

$$
 
 $$ \frac{N_{1}}{K_{1}} = 0 \frac{N_{1}}{K_{1}} = 1 \$\$

```{r}
# LV parameters
a <- c(0.02, 0.01)
r <- c(1, 1)
K <- c(3500,0.001)
p1 <- list(r, a, K)
N0 <- c(3500, 0.001) # N1[1] E N2[2]
t <- c(1:100)
```

```{r}
#Solving the equation

Out_LVeli <- ode(y = N0, times = t, func = LV_CoMu, parms = p1)
head(Out_LVcomp)

```

```{r}
df_LVmut <- pivot_longer(as.data.frame(Out_LVmut), cols = 2:3)
```

```{r}
ggplot(df_LVmut) +
  geom_line(aes(x = time, y = value, color = name)) +
  labs(x = "Time", y = "N", color = "Species") +
  theme_classic()
```

## Bistability

\$\$ \frac{N_{1}}{K_{1}} = 0 \frac{N_{1}}{K_{1}} = 0

$$
 
 $$ \frac{N_{1}}{K_{1}} = 0 \frac{N_{1}}{K_{1}} = 0 \$\$

```{r}
# LV parameters
a <- c(0.02, 0.01)
r <- c(1, 1)
K <- c(0.001,0.001)
p1 <- list(r, a, K)
N0 <- c(0.001, 0.001) # N1[1] E N2[2]
t <- c(1:100)
```

```{r}
#Solving the equation

Out_LVbis <- ode(y = N0, times = t, func = LV_CoMu, parms = p1)
head(Out_LVcomp)

```

```{r}
df_LVbis <- pivot_longer(as.data.frame(Out_LVbis), cols = 2:3)
```

```{r}
ggplot(df_LVbis) +
  geom_line(aes(x = time, y = value, color = name)) +
  labs(x = "Time", y = "N", color = "Species") +
  theme_classic()
```

## Coexistence

```{r}
# LV parameters
a <- c(0.02, 0.01)
r <- c(1, 1)
K <- c(3500,3000)
p1 <- list(r, a, K)
N0 <- c(3465, 2940) # N1[1] E N2[2]
t <- c(1:100)
```

```{r}
#Solving the equation

Out_LVcoex <- ode(y = N0, times = t, func = LV_CoMu, parms = p1)
head(Out_LVcoex)

```

```{r}
df_LVcoex <- pivot_longer(as.data.frame(Out_LVcoex), cols = 2:3)
```

```{r}
ggplot(df_LVcoex) +
  geom_line(aes(x = time, y = value, color = name)) +
  labs(x = "Time", y = "N", color = "Species") +
  theme_classic()
```
